### ISSUE TITLE
Exception in Xposed.log

### ISSUE THREAD

**Issue by F-i-f** [lj3lj3/XBridge#6]
Hello,
I'm using:
Nexus 5X
OmniROM 6.0.1 2016-08-24
Xposed v86
Xbridge 1.2

Just caught this exception in Xposed.log that crashed system UI.

```
10-05 08:05:00.212 E/Xposed  ( 1175): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.RemoteViews.setImageViewBitmap(int, android.graphics.Bitmap)' on a null object reference
10-05 08:05:00.212 E/Xposed  ( 1175):   at cz.babi.android.xposed.dynamicalarmicon2.XposedMod$1.beforeHookedMethod(XposedMod.java:180)
10-05 08:05:00.212 E/Xposed  ( 1175):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
10-05 08:05:00.212 E/Xposed  ( 1175):   at com.android.systemui.statusbar.NotificationData$Entry.<init>(<Xposed>)
10-05 08:05:00.212 E/Xposed  ( 1175):   at com.android.systemui.statusbar.BaseStatusBar.createNotificationViews(BaseStatusBar.java:1745)
10-05 08:05:00.212 E/Xposed  ( 1175):   at com.android.systemui.statusbar.phone.PhoneStatusBar.addNotification(PhoneStatusBar.java:1497)
10-05 08:05:00.212 E/Xposed  ( 1175):   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-05 08:05:00.212 E/Xposed  ( 1175):   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
10-05 08:05:00.212 E/Xposed  ( 1175):   at com.android.systemui.statusbar.phone.PhoneStatusBar.addNotification(<Xposed>)
10-05 08:05:00.212 E/Xposed  ( 1175):   at com.android.systemui.statusbar.BaseStatusBar$6$2.run(BaseStatusBar.java:491)
10-05 08:05:00.212 E/Xposed  ( 1175):   at android.os.Handler.handleCallback(Handler.java:739)
10-05 08:05:00.212 E/Xposed  ( 1175):   at android.os.Handler.dispatchMessage(Handler.java:95)
10-05 08:05:00.212 E/Xposed  ( 1175):   at android.os.Looper.loop(Looper.java:148)
10-05 08:05:00.212 E/Xposed  ( 1175):   at android.app.ActivityThread.main(ActivityThread.java:5422)
10-05 08:05:00.212 E/Xposed  ( 1175):   at java.lang.reflect.Method.invoke(Native Method)
10-05 08:05:00.212 E/Xposed  ( 1175):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-05 08:05:00.212 E/Xposed  ( 1175):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-05 08:05:00.212 E/Xposed  ( 1175):   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by lj3lj3** [comment]
This FC doesn't look like one of xbridge, report it to dynamicalarmicon2, I guess you have that module, thanks.
